version: '3.7'

services:
  # MongoDB
  saga_mongo:
    image: mongo:4.2.3

  saga_mongo_express:
    image: mongo-express
    ports:
      - ${SAGA_ME_PORT:-8081}:8081
    depends_on:
      - saga_mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: saga_mongo

  # Redis
  saga_redis:
    image: redis:5.0.7

  # Elasticsearch
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
#    environment:
#      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
#    healthcheck:
#      test: "curl --silent --fail localhost:9200/_cluster/health || exit 1"
#      interval: 5s
#      timeout: 2s
#      retries: 15

  # GraphQL server
  saga_app:
    build: .
    env_file: "etc/default/${ENV:-development}.env"
    ports:
      - ${SAGA_SERVER_PORT:-8080}:8080
    depends_on:
      - saga_mongo
      - saga_redis
    volumes:
      - ${PWD:-.}:/opt/app
      - saga_node_modules:/opt/app/node_modules

volumes:
  saga_node_modules:
